# Generated by Django 4.2.6 on 2023-10-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='position_id',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
