# Generated by Django 4.2.6 on 2023-10-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0002_remove_employees_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
