# Generated by Django 4.2.4 on 2023-09-28 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='Std_time',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='comments',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='ovt_time',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
