# Generated by Django 4.2.4 on 2023-09-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0002_timesheet_std_time_timesheet_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='Std_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='ovt_time',
            field=models.IntegerField(default=0),
        ),
    ]
