# Generated by Django 4.2.6 on 2023-10-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0003_alter_timesheet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
