# Generated by Django 4.2.4 on 2023-09-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0003_alter_timesheet_std_time_alter_timesheet_ovt_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='Std_time',
            new_name='Std_hr',
        ),
        migrations.RenameField(
            model_name='timesheet',
            old_name='ovt_time',
            new_name='ovt_hr',
        ),
    ]
