# Generated by Django 4.2.4 on 2023-09-28 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0004_rename_std_time_timesheet_std_hr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='Std_hr',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='ovt_hr',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='Std_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='ovt_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
