# Generated by Django 4.2.4 on 2023-09-25 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_information', '0005_auto_20220302_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monday_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tuesday_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('wednesday_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('thursday_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('friday_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('saturday_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sunday_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ovt_monday', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ovt_tuesday', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ovt_wednesday', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ovt_thursday', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ovt_friday', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ovt_saturday', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ovt_sunday', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_hour', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('employee', 'Employee')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
